# Generated by Django 5.0.7 on 2024-09-03 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0005_order_shipped'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='date_shippied',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
