# Generated by Django 5.0.7 on 2024-09-03 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0006_order_date_shippied'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='date_shippied',
            new_name='date_shipped',
        ),
    ]
