# Generated by Django 5.0.7 on 2024-07-20 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookt', '0002_alter_category_options_product_is_sale_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='salae_price',
            new_name='sale_price',
        ),
    ]
