# Generated by Django 5.0.7 on 2024-08-29 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookt', '0004_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='old_cart',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
